config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :jobs
  devise_scope :user do
    get "register", :to => 'devise/registrations#new', as: :register
    get "login", :to => 'devise/sessions#new', as: :login
    get "logout", :to => 'devise/sessions#destroy', as: :logout
  end

  get 'feed', to: 'jobs#index', as: :feed
  root :to =>  'jobs#index'

end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :user
 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # , :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :jobs
	
  def full_name
    first_name + " " + last_name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_filter :authenticate_user!, :except => [:show, :index]
  before_filter :set_job, only: [:show, :edit, :update, :destroy]
  


  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
    
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)
    @job.user_id = current_user.id

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:title, :description, :company_name, :details_link)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.haml
= form_for @job do |f|
  - if @job.errors.any?
    #error_explanation
      %h2= "#{pluralize(@job.errors.count, "error")} prohibited this job from being saved:"
      %ul
        - @job.errors.full_messages.each do |msg|
          %li= msg
  
  .field
    = f.label :title, "Job Title"
    = f.text_field :title
  .field
    = f.label :company_name, "Company Name"
    = f.text_field :company_name
  .field
    = f.label :description, "Job Description"
    = f.text_area :description
  .field
    = f.label :details_link, "Details Link (optional)"
    = f.text_field :details_link
  .actions
    = f.submit 'Submit'

app/views/jobs/edit.html.haml
%h2 Edit Job Posting

= render 'form'

= link_to 'Show', @job
\|
= link_to 'Back', jobs_path

app/views/jobs/index.html.haml
= link_to 'New Job', new_job_path, :class => "new_job_link"

%ul#jobs
  - @jobs.each do |job|
    %li
      = link_to(job, :class => "job_link") do
        %strong.job_title
          = job.title
        %span.description
          = job.description
    - if job.user == current_user      
      = link_to 'Edit', edit_job_path(job), :class => "Edit_link"

app/views/jobs/new.html.haml
%h2 New Job Posting

= render 'form'

= link_to 'Back', jobs_path

app/views/jobs/show.html.haml
%p#notice= notice
.job_show
	.job_header

		.show_job_title
			= @job.title
		.company_name
			= @job.company_name
		-# here the question i want to display the user that goes with the job that get posted.
		.user
			-if user_signed_in?
				Posted by
				= @job.user.profile_name
	.job_date
		POSTED ON
		%br
		= @job.created_at

	%p.job_description
		= @job.description
	= link_to 'Show More', @job.details_link, :class => "details_link"

	.job_links
		= link_to 'Edit', edit_job_path(@job)
		|
		= link_to 'Back', jobs_path

app/views/layouts/application.html.haml
!!!
%html
%head
  %title Easyjobs
  = stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Rokkitt', :rel => 'stylesheet', :type => 'text/css'
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
%body
  #wrapper
    #header
    = link_to root_url do
      %h1#logo
        Easy Jobs!
    #user_bar
      -if user_signed_in?
        Logged in as:
        = link_to  current_user.full_name ,edit_user_registration_path
        = link_to 'Sign out',  logout_path
      -else
        = link_to "Register", register_path
        |
        = link_to "Sign In", login_path
    %p.notice= notice
    %p.alert= alert
    .content= yield